name: 'Postgres Action'
description: 'include this action to setup postgress'
runs:
  db:
    image: postgres:13
    ports: ['5432:5432']
    env:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    options: >-
      --health-cmd pg_isready
      --health-interval 10s
      --health-timeout 5s
      --health-retries 5
